server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG